import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart3, BookOpen, BriefcaseBusiness, ChevronRight, ClipboardCheck, FileText, MessageCircle, Mic, Plus, Search, Send, ShieldAlert, Sparkles, Wrench } from 'lucide-react'
import './styles.css'

// In development Vite proxies this path to FastAPI, avoiding browser CORS
// differences when Vite selects 5173, 5174, or another free local port.
// A deployed build can still set VITE_API_BASE_URL explicitly.
const API = import.meta.env.VITE_API_BASE_URL || '/api'
const api = async (path:string, options:RequestInit={}) => { const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));const d=body.detail;throw new Error(Array.isArray(d)?d.map((x:any)=>x.msg).join('; '):(typeof d==='string'?d:`Request failed (${response.status})`))}return response.json() }
type Tab='today'|'assistant'|'library'|'job'|'operations'
type Task={job_id:number;title:string;customer_name:string;status:string;equipment_model:string;error_code?:string|null;service_address?:string|null;scheduled_for:string;brief_ready:boolean}
type Brief={summary:string;safety_flags:string[]}
type Chat={id:number;role:string;content:string;created_at:string;trace?:string[]}

const Tabs=({tab,setTab}:{tab:Tab;setTab:(tab:Tab)=>void})=><nav className="tabs">{([{id:'today',label:'Today',icon:BriefcaseBusiness},{id:'assistant',label:'Assistant',icon:MessageCircle},{id:'library',label:'Library',icon:BookOpen},{id:'job',label:'Job',icon:ClipboardCheck},{id:'operations',label:'Operations',icon:BarChart3}] as const).map(item=>{const Icon=item.icon;return <button key={item.id} className={tab===item.id?'active':''} onClick={()=>setTab(item.id)}><Icon size={17}/><span>{item.label}</span></button>})}</nav>

function App(){const [tab,setTab]=useState<Tab>('today');const [tasks,setTasks]=useState<Task[]>([]);const [selected,setSelected]=useState<Task|null>(null);const [brief,setBrief]=useState<Brief|null>(null);const [runId,setRunId]=useState<number|null>(null);const [conversationId,setConversationId]=useState<number|null>(null);const [guidedStarted,setGuidedStarted]=useState(false);const [messages,setMessages]=useState<Chat[]>([]);const [input,setInput]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [library,setLibrary]=useState<any[]>([]);const [query,setQuery]=useState('');const [summary,setSummary]=useState<any>(null);const [dashboard,setDashboard]=useState<any>(null);const [estimates,setEstimates]=useState<any[]>([]);const [newJob,setNewJob]=useState(false);const [form,setForm]=useState({manufacturer:'Carrier',model:'MODEL-NC',type:'split_system',site:'Field visit',symptom:'AC is not cooling and blows warm air.',error:'E101'});
 const loadTasks=async()=>{try{const data=await api('/technician/tasks');setTasks(data);if(!selected&&data[0])selectTask(data[0])}catch(e:any){setNotice(e.message)}};
 const selectTask=async(task:Task)=>{setSelected(task);setBrief(null);setSummary(null);setRunId(null);setConversationId(null);setGuidedStarted(false);setMessages([]);try{setBrief(await api(`/jobs/${task.job_id}/brief`))}catch(e:any){setNotice(e.message)}};
 useEffect(()=>{loadTasks()},[]);
 const loadMessages=async(id:number)=>setMessages(await api(`/agent-runs/${id}/messages`));
 const startAssistant=async()=>{if(!selected)return;setBusy(true);setNotice('');try{const created=await api(`/jobs/${selected.job_id}/agent-runs`,{method:'POST',body:JSON.stringify({max_steps:16})});setRunId(created.id);setNotice('Assistant ready. Ask a question, or start guided diagnosis when you want structured checks.')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const startGuidedDiagnosis=async()=>{if(!runId)return;setBusy(true);setNotice('Guided diagnosis is running. Waiting for the model (up to 45 seconds)…');try{const result=await api(`/agent-runs/${runId}/start`,{method:'POST'});setGuidedStarted(true);await loadMessages(runId);setNotice(result.status==='waiting_for_technician'?'Guided diagnosis is ready for the next field measurement.':`Guided diagnosis: ${result.status}.`)}catch(e:any){setNotice(`Could not start guided diagnosis: ${e.message}`)}finally{setBusy(false)}};
 const send=async()=>{if(!selected||!input.trim())return;const message=input.trim();setBusy(true);setInput('');setMessages(old=>[...old,{id:Date.now(),role:'technician',content:message,created_at:new Date().toISOString()}]);try{const result=await api('/assistant/turns',{method:'POST',body:JSON.stringify({message,conversation_id:conversationId,job_id:conversationId?undefined:selected.job_id})});setConversationId(result.conversation_id);const trace=[`Routed workflow: ${result.selected_skill}`,`Checked verified history: ${result.similar_cases.length} match(es)`,`Checked curated knowledge: ${result.knowledge_entries.length} match(es)`,`Checked service documents${result.retrieval_warnings.length?' with broader fallback':''}`,`Saved conversation and work-order trace to database`,...result.retrieval_warnings];setMessages(old=>[...old,{id:Date.now()+1,role:'assistant',content:result.answer,created_at:new Date().toISOString(),trace}]);setNotice(`Synced to work order #${result.job_id}`)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const loadOperations=async()=>{setBusy(true);try{const [dash,items]=await Promise.all([api('/operations/dashboard'),api('/estimates')]);setDashboard(dash);setEstimates(items)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const createJob=async()=>{setBusy(true);try{const equipment=await api('/equipment',{method:'POST',body:JSON.stringify({manufacturer:form.manufacturer,model_number:form.model,equipment_type:form.type})});const job=await api('/jobs',{method:'POST',body:JSON.stringify({customer_name:form.site,equipment_id:equipment.id,technician_notes:form.symptom,error_code:form.error||null})});const task:Task={job_id:job.id,title:form.symptom,customer_name:form.site,status:'open',equipment_model:form.model,error_code:form.error,scheduled_for:new Date().toISOString(),brief_ready:false};await selectTask(task);setTasks([task,...tasks]);setNewJob(false);setTab('assistant');setNotice('New job created. Start the assistant when ready.')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const search=async()=>{if(!query.trim())return;setBusy(true);try{setLibrary(await api('/manuals/search',{method:'POST',body:JSON.stringify({query,top_k:6})}))}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const makeSummary=async()=>{if(!selected)return;setBusy(true);try{setSummary(await api(`/jobs/${selected.job_id}/summary`,{method:'POST'}));setNotice('Service summary saved.')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 return <main><header className="app-header"><div className="app-brand"><span><Wrench size={16}/></span>fieldwise</div><div className="job-context">{selected?<>Job #{selected.job_id}<i/> {selected.customer_name}</>: 'HVAC operations workspace'}</div><button className="new-job" onClick={()=>setNewJob(true)}><Plus size={15}/>New job</button></header><div className="desktop-nav"><Tabs tab={tab} setTab={t=>{setTab(t);if(t==='operations')loadOperations()}}/></div><section className="app-shell">{tab==='today'&&<Today tasks={tasks} selected={selected} onSelect={task=>{selectTask(task);setTab('job')}} onAssistant={task=>{selectTask(task);setTab('assistant')}}/>}{tab==='assistant'&&<Assistant selected={selected} brief={brief} runId={runId} guidedStarted={guidedStarted} messages={messages} input={input} setInput={setInput} busy={busy} notice={notice} onStart={startAssistant} onStartGuided={startGuidedDiagnosis} onSend={send}/>} {tab==='library'&&<Library query={query} setQuery={setQuery} results={library} busy={busy} onSearch={search}/>} {tab==='job'&&<Job selected={selected} brief={brief} summary={summary} busy={busy} onSummary={makeSummary}/>} {tab==='operations'&&<Operations dashboard={dashboard} estimates={estimates} busy={busy}/>}<p className="notice">{notice}</p></section><div className="mobile-nav"><Tabs tab={tab} setTab={t=>{setTab(t);if(t==='operations')loadOperations()}}/></div>{newJob&&<NewJob form={form} setForm={setForm} busy={busy} onClose={()=>setNewJob(false)} onCreate={createJob}/>}</main>}

function Today({tasks,selected,onSelect,onAssistant}:{tasks:Task[];selected:Task|null;onSelect:(t:Task)=>void;onAssistant:(t:Task)=>void}){return <section className="view today"><div className="view-head"><div><p className="kicker">FIELD SCHEDULE</p><h1>Today</h1><p>Your active HVAC service calls.</p></div><span className="date-chip">{new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date())}</span></div>{tasks.length?<div className="task-list">{tasks.map(task=><article key={task.job_id} className={selected?.job_id===task.job_id?'task-card selected':'task-card'} onClick={()=>onSelect(task)}><div className="task-main"><span className="task-status">{task.status.replace(/_/g,' ')}</span><h2>{task.title}</h2><p>{task.customer_name} · {task.equipment_model}</p><small>{task.service_address||'Location pending'}{task.error_code?` · ${task.error_code}`:''}</small></div><div className="task-action">{task.brief_ready&&<span className="ready"><Mic size={13}/>Brief ready</span>}<button onClick={e=>{e.stopPropagation();onAssistant(task)}}>Open <ChevronRight size={16}/></button></div></article>)}</div>:<Empty title="No active jobs" text="Create a job to start a field assessment."/>}</section>}

function Assistant({selected,brief,runId,guidedStarted,messages,input,setInput,busy,notice,onStart,onStartGuided,onSend}:{selected:Task|null;brief:Brief|null;runId:number|null;guidedStarted:boolean;messages:Chat[];input:string;setInput:(v:string)=>void;busy:boolean;notice:string;onStart:()=>void;onStartGuided:()=>void;onSend:()=>void}){if(!selected)return <Empty title="Select a job first" text="Open a task from Today or create a new job."/>;return <section className="view assistant"><div className="assistant-top"><div><p className="kicker">FIELD ASSISTANT</p><h1>{selected.equipment_model}</h1><p>{selected.title}</p></div>{!runId?<button className="dark-button" onClick={onStart} disabled={busy}><Sparkles size={16}/>{busy?'Opening…':'Open assistant'}</button>:!guidedStarted&&<button className="dark-button" onClick={onStartGuided} disabled={busy}><Sparkles size={16}/>{busy?'Starting…':'Start guided diagnosis'}</button>}</div>{notice&&<p className="assistant-notice" role="status">{notice}</p>}{brief&&<div className="brief"><div><b>Arrival brief</b><p>{brief.summary}</p></div>{brief.safety_flags.length>0&&<div className="brief-warning"><ShieldAlert size={15}/>{brief.safety_flags.join(' · ')}</div>}</div>}<div className="chat">{!runId?<div className="chat-empty"><MessageCircle size={25}/><h2>Ask from the field</h2><p>Open the assistant for natural conversation, then start guided diagnosis only when you need structured checks.</p></div>:messages.length?<>{messages.map(message=><div key={message.id} className={`message-row ${message.role==='technician'?'tech':''}`}>{message.trace&&<details className="agent-trace"><summary><Sparkles size={13}/>Agent activity</summary>{message.trace.map((item,index)=><p key={index}>{item}</p>)}</details>}<div className={`bubble ${message.role==='technician'?'tech':'assistant'}`}>{message.content}</div></div>)}{busy&&<div className="bubble assistant">Checking records and documents…</div>}</>:<div className="chat-empty"><MessageCircle size={25}/><h2>What are you seeing?</h2><p>Ask about the error code, likely causes, or the safest next check.</p></div>}</div><div className="composer"><input disabled={!runId||busy} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')onSend()}} placeholder={runId?'Ask a question or describe an observation…':'Open assistant to chat'}/><button disabled={!runId||busy||!input.trim()} onClick={onSend}><Send size={17}/></button></div></section>}

function Library({query,setQuery,results,busy,onSearch}:{query:string;setQuery:(v:string)=>void;results:any[];busy:boolean;onSearch:()=>void}){return <section className="view library"><div className="view-head"><div><p className="kicker">PRODUCT LIBRARY</p><h1>Find the right manual</h1><p>Search model numbers, error codes, or equipment terms.</p></div></div><div className="search-box"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')onSearch()}} placeholder="e.g. Carrier E101 or CA15NA060-A"/><button onClick={onSearch} disabled={busy}>Search</button></div><div className="manual-results">{results.map((item,index)=><article key={item.id||index}><span>p. {item.page}</span><div><h2>{item.title||item.document}</h2><p>{item.manufacturer} · {item.section||'Manual excerpt'}</p><blockquote>{item.text}</blockquote></div><ChevronRight size={18}/></article>)}{!results.length&&<Empty title="Search manuals and product data" text="Results will be grounded in the local manual index."/>}</div></section>}

function Job({selected,brief,summary,busy,onSummary}:{selected:Task|null;brief:Brief|null;summary:any;busy:boolean;onSummary:()=>void}){if(!selected)return <Empty title="No job selected" text="Choose a task from Today."/>;return <section className="view job"><div className="view-head"><div><p className="kicker">JOB DETAIL</p><h1>{selected.customer_name}</h1><p>{selected.equipment_model} · {selected.status}</p></div><button className="dark-button" onClick={onSummary} disabled={busy}><FileText size={16}/>{busy?'Generating…':'Generate summary'}</button></div><div className="job-grid"><article><span className="label">Reported issue</span><p>{selected.title}</p><span className="label">Equipment</span><p>{selected.equipment_model}{selected.error_code?` · ${selected.error_code}`:''}</p></article><article><span className="label">Arrival brief</span><p>{brief?.summary||'Open this task to prepare its brief.'}</p></article></div>{summary?<article className="summary"><div><span className="ready"><ClipboardCheck size={14}/>Summary ready</span><button onClick={()=>navigator.clipboard.writeText(summary.content)}>Copy</button></div><pre>{summary.content}</pre></article>:<Empty title="Finish strong" text="Generate a concise service summary after your diagnostic work."/>}</section>}

function Operations({dashboard,estimates,busy}:{dashboard:any;estimates:any[];busy:boolean}){if(busy&&!dashboard)return <Empty title="Loading operations" text="Reading jobs, estimates, and follow-up queues."/>;return <section className="view operations"><div className="view-head"><div><p className="kicker">BACK OFFICE</p><h1>Revenue operations</h1><p>Estimate pipeline, human review, and automated follow-ups.</p></div></div>{dashboard&&<div className="metric-grid"><article><span>Open pipeline</span><b>${dashboard.open_pipeline_value.toLocaleString()}</b><small>{dashboard.open_estimates} estimates</small></article><article><span>Won revenue</span><b>${dashboard.won_revenue.toLocaleString()}</b><small>Recorded outcomes</small></article><article><span>Follow-ups</span><b>{dashboard.queued_follow_ups}</b><small>{dashboard.needs_review} need review</small></article><article><span>Automation</span><b>{dashboard.automation_rate}%</b><small>{dashboard.active_jobs} active jobs</small></article></div>}<div className="estimate-list">{estimates.map(item=><article key={item.id}><div><span className="task-status">{item.status}</span><h2>Estimate #{item.id}</h2><p>{item.description}</p></div><b>${item.amount.toLocaleString()}</b></article>)}{!estimates.length&&<Empty title="No estimates yet" text="Create estimates through the API to populate the follow-up pipeline."/>}</div></section>}

function NewJob({form,setForm,busy,onClose,onCreate}:{form:any;setForm:(f:any)=>void;busy:boolean;onClose:()=>void;onCreate:()=>void}){const set=(key:string,value:string)=>setForm({...form,[key]:value});return <div className="modal-backdrop"><section className="new-job-modal"><div><p className="kicker">NEW FIELD JOB</p><h2>Start with what you know.</h2></div><div className="two"><label>Manufacturer<input value={form.manufacturer} onChange={e=>set('manufacturer',e.target.value)}/></label><label>Model<input value={form.model} onChange={e=>set('model',e.target.value)}/></label></div><label>Equipment type<select value={form.type} onChange={e=>set('type',e.target.value)}><option value="split_system">Split system</option><option value="heat_pump">Heat pump</option><option value="rooftop_unit">Rooftop unit</option></select></label><label>Site / customer<input value={form.site} onChange={e=>set('site',e.target.value)}/></label><label>What are you seeing?<textarea value={form.symptom} onChange={e=>set('symptom',e.target.value)}/></label><label>Error code <input value={form.error} onChange={e=>set('error',e.target.value)}/></label><div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="dark-button" onClick={onCreate} disabled={busy}>{busy?'Creating…':'Create job'}</button></div></section></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><Wrench size={25}/><h2>{title}</h2><p>{text}</p></div>}
createRoot(document.getElementById('root')!).render(<App />)
